#:kivy 1.8

<Label>
    color: (0,0,0,1)
    color_disables: (0,0,0,1)

<ContactItem>:
    orientation: "horizontal"
    root: root
    size_hint: [1, 0.1]
    Label:
        text: root.name
    Label:
        text: root.email
    Label:
        text: root.subject
    Button:
        text: "Anschreiben"
        on_press: root.trigger_write_mail()
    Button:
        text: "Löschen"
        on_press: root.trigger_delete()
