#:kivy 1.8

<DeletePopupContacts>:
    size_hint: .5, .5
    auto_dismiss: False
    title: 'Löschen bestätigen'
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Möchten Sie diesen Kontakt wirklich löschen?"
        Button:
            text: 'Nein'
            on_press: root.dismiss()
        Button:
            text: 'Ja'
            on_press: root.deleteContact()
            on_press: root.dismiss()