#:kivy 1.8

<ResetPopup>:
    size_hint: .5, .5
    auto_dismiss: False
    title: 'Reset bestätigen'
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Möchten Sie das Programm wirklich auf den \nursprünglichen Zustand zurücksetzen?"
        Button:
            background_normal: "GUI/Icons/iCancel.png"
            on_press: root.dismiss()
        Button:
            background_normal: "GUI/Icons/iConfirm.png"
            on_press: print root.parent.parent