#:kivy 1.7.2

<WriteLayout>:
    buttons: []
    BoxLayout:
        BoxLayout:
            orientation: "vertical"

            GridLayout:
                size_hint: [1, 0.1]
                rows: 1
                Button:
                    text: "Previous"
                Button:
                    text: "Save"
                Button:
                    text: "Next"
            TextInput:
                text: "Input"

