"""Adding inboxes

Revision ID: 31821dd1c857
Revises: 5a0d641e7a3b
Create Date: 2014-06-04 18:56:58.313288

"""

# revision identifiers, used by Alembic.
revision = '31821dd1c857'
down_revision = '5a0d641e7a3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userMail', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('server', sa.String(length=255), nullable=True),
    sa.Column('port', sa.String(length=255), nullable=True),
    sa.Column('protocol', sa.String(length=255), nullable=True),
    sa.Column('authProtocol', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inboxes_password', 'inboxes', ['password'], unique=False)
    op.add_column(u'mails', sa.Column('inboxId', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'mails', 'inboxId')
    op.drop_index('ix_inboxes_password', 'inboxes')
    op.drop_table('inboxes')
    ### end Alembic commands ###
