"""Create first table

Revision ID: 5717d24bd729
Revises: None
Create Date: 2014-06-04 17:52:52.519014

"""

# revision identifiers, used by Alembic.
revision = '5717d24bd729'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mail_name', 'mail', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mail_name', 'mail')
    op.drop_table('mail')
    ### end Alembic commands ###
