"""Updating mail table

Revision ID: 5a0d641e7a3b
Revises: 5717d24bd729
Create Date: 2014-06-04 18:42:07.175018

"""

# revision identifiers, used by Alembic.
revision = '5a0d641e7a3b'
down_revision = '5717d24bd729'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('_from', sa.String(length=255), nullable=True),
    sa.Column('to', sa.String(length=255), nullable=True),
    sa.Column('cc', sa.Text(), nullable=True),
    sa.Column('bcc', sa.Text(), nullable=True),
    sa.Column('inReplyTo', sa.String(length=255), nullable=True),
    sa.Column('messageId', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mails_inReplyTo', 'mails', ['inReplyTo'], unique=False)
    op.create_index('ix_mails_messageId', 'mails', ['messageId'], unique=False)
    op.create_index('ix_mails_subject', 'mails', ['subject'], unique=False)
    op.drop_table(u'mail')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'mail',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.drop_index('ix_mails_subject', 'mails')
    op.drop_index('ix_mails_messageId', 'mails')
    op.drop_index('ix_mails_inReplyTo', 'mails')
    op.drop_table('mails')
    ### end Alembic commands ###
