"""Adding Contacts, and syncing Inbox db

Revision ID: 78912abf395
Revises: 31821dd1c857
Create Date: 2014-06-19 20:05:59.157624

"""

# revision identifiers, used by Alembic.
revision = '78912abf395'
down_revision = '31821dd1c857'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=255), nullable=True),
    sa.Column('lastName', sa.String(length=255), nullable=True),
    sa.Column('emailAddress', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_lastName', 'contacts', ['lastName'], unique=False)
    op.add_column(u'inboxes', sa.Column('account', sa.String(length=255), nullable=True))
    op.drop_column(u'inboxes', u'authProtocol')
    op.add_column(u'mails', sa.Column('message', sa.String(length=255), nullable=True))
    op.drop_column(u'mails', u'messageId')
    op.create_index('ix_mails_message', 'mails', ['message'], unique=False)
    op.drop_index('ix_mails_messageId', 'mails')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_mails_messageId', 'mails', [u'messageId'], unique=False)
    op.drop_index('ix_mails_message', 'mails')
    op.add_column(u'mails', sa.Column(u'messageId', sa.VARCHAR(length=255), nullable=True))
    op.drop_column(u'mails', 'message')
    op.add_column(u'inboxes', sa.Column(u'authProtocol', sa.VARCHAR(length=255), nullable=True))
    op.drop_column(u'inboxes', 'account')
    op.drop_index('ix_contacts_lastName', 'contacts')
    op.drop_table('contacts')
    ### end Alembic commands ###
